-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 12:24:49 2018
-- Model: SITIC    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sitic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sitic` ;

-- -----------------------------------------------------
-- Schema sitic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sitic` DEFAULT CHARACTER SET utf8mb4 ;
USE `sitic` ;

-- -----------------------------------------------------
-- Table `sitic`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`department` ;

CREATE TABLE IF NOT EXISTS `sitic`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DEPARTAMENTO',
  `department` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DEPARTAMENTO',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT 'DEPARTAMENTO PADRE',
  `status` INT(11) NOT NULL COMMENT 'ESTADO DEPARTAMENTO',
  PRIMARY KEY (`id`),
  INDEX `fk_department_department1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_department_department1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`documents` ;

CREATE TABLE IF NOT EXISTS `sitic`.`documents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DOCUMENTO',
  `filename` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DOCUMENTO',
  `filetype` VARCHAR(45) NOT NULL COMMENT 'TIPO DOCUMENTO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE DOCUMENTO',
  `date` DATETIME NOT NULL COMMENT 'FECHA',
  `external_id` INT(11) NOT NULL COMMENT 'ID RELACION',
  `external_type` VARCHAR(45) NOT NULL COMMENT 'TIPO RELACION',
  `username` VARCHAR(255) NOT NULL COMMENT 'NOMBRE USUARIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `auth_key` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'CLAVE',
  `status` SMALLINT(6) NOT NULL DEFAULT '1' COMMENT 'ESTADO',
  `created_at` INT NOT NULL COMMENT 'CREADO',
  `updated_at` INT(11) NOT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `auth_key` (`auth_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`inv_manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`inv_manufacturers` ;

CREATE TABLE IF NOT EXISTS `sitic`.`inv_manufacturers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID FABRICANTE',
  `manufacturer` VARCHAR(45) NOT NULL COMMENT 'NOMBRE FABRICANTE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `manufacturer_UNIQUE` (`manufacturer` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`inv_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`inv_models` ;

CREATE TABLE IF NOT EXISTS `sitic`.`inv_models` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID MODELO',
  `model` VARCHAR(45) NOT NULL COMMENT 'NOMBRE MODELO',
  `consumables` LONGTEXT NULL DEFAULT NULL COMMENT 'CONSUMIBLES',
  `inv_manufacturers_id` INT(11) NOT NULL COMMENT 'ID FABRICANTE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC),
  INDEX `fk_inv_models_inv_manufacturers1_idx` (`inv_manufacturers_id` ASC),
  CONSTRAINT `fk_inv_models_inv_manufacturers1`
    FOREIGN KEY (`inv_manufacturers_id`)
    REFERENCES `sitic`.`inv_manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`inv_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`inv_purchase` ;

CREATE TABLE IF NOT EXISTS `sitic`.`inv_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID COMPRA',
  `code` VARCHAR(45) NOT NULL COMMENT 'CODIGO COMPRA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE COMPRA',
  `date` DATE NOT NULL COMMENT 'FECHA RECEPCION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_purchase_user1_idx` (`username` ASC),
  CONSTRAINT `fk_inv_purchase_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`inv_purchase_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`inv_purchase_item` ;

CREATE TABLE IF NOT EXISTS `sitic`.`inv_purchase_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ITEM',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE ITEM',
  `amount` FLOAT(11) NOT NULL COMMENT 'PRECIO ITEM',
  `control_code` VARCHAR(100) NULL DEFAULT NULL COMMENT 'CODIGO CONTROL',
  `inv_models_id` INT(11) NOT NULL COMMENT 'ID MODELO',
  `serial_number` VARCHAR(45) NOT NULL COMMENT 'NUMERO SERIE',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_purchase_item_inv_purchase1_idx` (`inv_purchase_id` ASC),
  INDEX `fk_inv_purchase_item_inv_models1_idx` (`inv_models_id` ASC),
  CONSTRAINT `fk_inv_purchase_item_inv_models1`
    FOREIGN KEY (`inv_models_id`)
    REFERENCES `sitic`.`inv_models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_purchase_item_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`inv_item_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`inv_item_user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`inv_item_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `inv_purchase_item_id` INT(11) NOT NULL COMMENT 'ID ITEM',
  `date_asigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE ASIGNACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_inv_purchase_item_inv_purchase_item1_idx` (`inv_purchase_item_id` ASC),
  INDEX `fk_inv_item_user_user1_idx` (`username` ASC),
  CONSTRAINT `fk_inv_item_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_inv_purchase_item_inv_purchase_item1`
    FOREIGN KEY (`inv_purchase_item_id`)
    REFERENCES `sitic`.`inv_purchase_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`it_incidents_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_incidents_reports` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_incidents_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID INCIDENTE',
  `subject` VARCHAR(255) NOT NULL COMMENT 'ASUNTO',
  `issue` LONGTEXT NOT NULL COMMENT 'DETALLE PROBLEMA',
  `date_reported` DATETIME NOT NULL COMMENT 'FECHA REPORTE',
  `date_solved` DATETIME NULL DEFAULT NULL COMMENT 'FECHA SOLUCION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_incidents_reports_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_incidents_reports_user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_incidents_reports_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `it_incidents_reports_id` INT(11) NOT NULL COMMENT 'ID REPORTE INCIDENTE',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_it_incidents_reports_it_incidents_reports1_idx` (`it_incidents_reports_id` ASC),
  INDEX `fk_it_incidents_reports_user_user1_idx` (`username` ASC),
  CONSTRAINT `fk_it_incidents_reports_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_it_incidents_reports_it_incidents_reports1`
    FOREIGN KEY (`it_incidents_reports_id`)
    REFERENCES `sitic`.`it_incidents_reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`it_processes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_processes` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_processes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID PROCESO',
  `process` VARCHAR(255) NOT NULL COMMENT 'NOMBRE PROCESO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE PROCESO',
  `metrics` LONGTEXT NOT NULL COMMENT 'METRICA EVALUACION',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CIERRE',
  `magnitude` INT(11) NOT NULL COMMENT 'IMPORTANCIA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID PROYECTO',
  `code` VARCHAR(45) NOT NULL COMMENT 'CODIGO PROYECTO',
  `project` VARCHAR(255) NOT NULL COMMENT 'NOMBRE PROYECTO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION PROYECTO',
  `amount` FLOAT(11) NOT NULL COMMENT 'MONTO COSTO',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CIERRE',
  `status` INT(11) NOT NULL COMMENT 'ESTADO PROYECTO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_processes_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_processes_projects` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_processes_projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO\n',
  `status` INT(11) NOT NULL COMMENT 'ESTADO\n',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_it_projects_it_projects1_idx` (`it_projects_id` ASC),
  INDEX `fk_it_processes_has_it_projects_it_processes1_idx` (`it_processes_id` ASC),
  CONSTRAINT `fk_it_processes_has_it_projects_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_it_projects_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_processes_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_processes_purchase` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_processes_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_inv_purchase_inv_purchase1_idx` (`inv_purchase_id` ASC),
  INDEX `fk_it_processes_has_inv_purchase_it_processes1_idx` (`it_processes_id` ASC),
  CONSTRAINT `fk_it_processes_has_inv_purchase_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_inv_purchase_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_services` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID SERVICIO',
  `service` VARCHAR(255) NOT NULL COMMENT 'NOMBRE SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION SERVICIO',
  `type` VARCHAR(255) NOT NULL COMMENT 'TIPO SERVICIO',
  `date_renovation` DATE NULL DEFAULT NULL COMMENT 'FECHA RENOVACION',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CULMINACION',
  `stakeholders` VARCHAR(255) NOT NULL COMMENT 'BENEFICIARIOS',
  `magnitude` INT(11) NOT NULL COMMENT 'IMPORTANCIA DEL SERVICIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO PROCESO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_processes_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_processes_services` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_processes_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_it_services_it_services1_idx` (`it_services_id` ASC),
  INDEX `fk_it_processes_has_it_services_it_processes1_idx` (`it_processes_id` ASC),
  CONSTRAINT `fk_it_processes_has_it_services_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_it_services_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_processes_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_processes_user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_processes_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE ASIGNACION',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_it_processes_it_processes1_idx` (`it_processes_id` ASC),
  INDEX `fk_it_processes_user_user1_idx` (`username` ASC),
  CONSTRAINT `fk_it_processes_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_it_processes_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects_parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects_parents` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects_parents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'CODIGO PROYECTO',
  `parent_id` INT(11) NOT NULL COMMENT 'PROYECTO RELACIONADO',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO RELACION',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_has_it_projects_it_projects2_idx` (`it_projects_id` ASC),
  INDEX `fk_it_projects_has_it_projects_it_projects1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_it_projects_has_it_projects_it_projects1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_has_it_projects_it_projects2`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects_purchase` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_has_inv_purchase_inv_purchase1_idx` (`inv_purchase_id` ASC),
  INDEX `fk_it_projects_has_inv_purchase_it_projects1_idx` (`it_projects_id` ASC),
  CONSTRAINT `fk_it_projects_has_inv_purchase_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_has_inv_purchase_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects_services` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_it_projects_it_projects1_idx` (`it_projects_id` ASC),
  INDEX `fk_it_services_has_it_projects_it_services1_idx` (`it_services_id` ASC),
  CONSTRAINT `fk_it_services_has_it_projects_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_has_it_projects_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects_stages` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects_stages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO ETAPA',
  `project_stage` VARCHAR(255) NOT NULL COMMENT 'ETAPA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `percent` DOUBLE NOT NULL COMMENT 'PORCENTAJE',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_stages_it_projects1_idx` (`it_projects_id` ASC),
  CONSTRAINT `fk_it_projects_stages_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_projects_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_projects_user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_projects_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION ASIGNACION',
  `date_asigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_has_user_it_projects1_idx` (`it_projects_id` ASC),
  INDEX `fk_it_projects_user_user1_idx` (`username` ASC),
  CONSTRAINT `fk_it_projects_has_user_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_reports_powerbi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_reports_powerbi` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_reports_powerbi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID REPORTE',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `url` LONGTEXT NOT NULL COMMENT 'URL',
  `html_iframe` LONGTEXT NOT NULL COMMENT 'HTML IFRAME',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_services_affectations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_services_affectations` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_services_affectations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID AFECTACION',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `it_incidents_reports_id` INT(11) NOT NULL COMMENT 'ID INCIDENTE',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `affected_users` INT(11) NOT NULL COMMENT 'USUARIOS AFECTADOS',
  `affected_time` INT(11) NOT NULL COMMENT 'TIEMPO MINUTOS',
  `type` INT(11) NOT NULL COMMENT 'TIPO AFECTACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_it_incidents_reports_it_incidents_report_idx` (`it_incidents_reports_id` ASC),
  INDEX `fk_it_services_has_it_incidents_reports_it_services1_idx` (`it_services_id` ASC),
  CONSTRAINT `fk_it_services_has_it_incidents_reports_it_incidents_reports1`
    FOREIGN KEY (`it_incidents_reports_id`)
    REFERENCES `sitic`.`it_incidents_reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_has_it_incidents_reports_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_services_availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_services_availability` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_services_availability` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DISPONIBILIDAD',
  `it_services_id` INT(11) NOT NULL,
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `date_start` DATE NOT NULL COMMENT 'FECHA INICIO',
  `date_end` DATE NOT NULL COMMENT 'FECHA FIN',
  `availability_time` INT(11) NOT NULL COMMENT 'TIEMPO MINUTOS',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_availability_it_services1_idx` (`it_services_id` ASC),
  CONSTRAINT `fk_it_services_availability_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_services_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_services_result` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_services_result` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RESULTADO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `year` INT(11) NOT NULL COMMENT 'AÑO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `percent` DOUBLE NOT NULL COMMENT 'PORCENTAJE',
  `date` DATETIME NOT NULL COMMENT 'FECHA',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_result_it_services1_idx` (`it_services_id` ASC),
  CONSTRAINT `fk_it_services_result_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`it_services_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`it_services_user` ;

CREATE TABLE IF NOT EXISTS `sitic`.`it_services_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION ASIGNACION',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_user_it_services1_idx` (`it_services_id` ASC),
  INDEX `fk_it_services_user_user1_idx` (`username` ASC),
  CONSTRAINT `fk_it_services_has_user_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`logs` ;

CREATE TABLE IF NOT EXISTS `sitic`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` VARCHAR(255) NOT NULL COMMENT 'TIPO',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  `datetime` DATETIME NOT NULL COMMENT 'FECHA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `ipaddress` VARCHAR(255) NULL COMMENT 'IP',
  `external_id` VARCHAR(255) NULL COMMENT 'ID EXTERNO',
  `external_type` VARCHAR(255) NULL COMMENT 'TIPO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitic`.`migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`migration` ;

CREATE TABLE IF NOT EXISTS `sitic`.`migration` (
  `version` VARCHAR(180) NOT NULL COMMENT 'VERSION',
  `apply_time` INT(11) NULL DEFAULT NULL COMMENT 'FECHA',
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`auth_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`auth_rule` ;

CREATE TABLE IF NOT EXISTS `sitic`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`auth_item` ;

CREATE TABLE IF NOT EXISTS `sitic`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `type` SMALLINT(6) NOT NULL COMMENT 'TIPO',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'DETALLE',
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL DEFAULT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `idx-auth_item-type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `sitic`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_item_child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`auth_item_child` ;

CREATE TABLE IF NOT EXISTS `sitic`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL PADRE',
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL HIJO',
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`auth_assignment` ;

CREATE TABLE IF NOT EXISTS `sitic`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `auth_assignment_user_id_idx` (`user_id` ASC),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`registration` ;

CREATE TABLE IF NOT EXISTS `sitic`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `company` VARCHAR(255) NOT NULL COMMENT 'EMPRESA',
  `mail` VARCHAR(255) NOT NULL COMMENT 'EMAIL CONTACTO',
  `address` VARCHAR(255) NOT NULL COMMENT 'DIRECCION',
  `phone` VARCHAR(45) NOT NULL COMMENT 'TELEFONO',
  `status` SMALLINT(6) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'CREADO\n',
  `updated_at` DATETIME NOT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitic`.`user_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sitic`.`user_department` ;

CREATE TABLE IF NOT EXISTS `sitic`.`user_department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `department_id` INT(11) NOT NULL COMMENT 'ID DEPARTAMENTO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_department_department1_idx` (`department_id` ASC),
  INDEX `fk_user_department_user1_idx` (`username` ASC),
  CONSTRAINT `fk_user_department_user1`
    FOREIGN KEY (`username`)
    REFERENCES `sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_department_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

USE `sitic` ;

-- -----------------------------------------------------
-- Placeholder table for view `sitic`.`inv_items_assigned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`inv_items_assigned` (`inv_purchase_id` INT, `id` INT, `username` INT, `inv_purchase_item_id` INT, `date_asigned` INT, `date_released` INT, `description` INT, `status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `sitic`.`inv_items_unassigned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`inv_items_unassigned` (`id` INT, `description` INT, `amount` INT, `control_code` INT, `inv_models_id` INT, `serial_number` INT, `inv_purchase_id` INT);

-- -----------------------------------------------------
-- View `sitic`.`inv_items_assigned`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `sitic`.`inv_items_assigned` ;
DROP TABLE IF EXISTS `sitic`.`inv_items_assigned`;
USE `sitic`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`sitic`@`localhost` SQL SECURITY DEFINER VIEW `sitic`.`inv_items_assigned` AS select distinct `sitic`.`inv_purchase_item`.`inv_purchase_id` AS `inv_purchase_id`,`sitic`.`inv_item_user`.`id` AS `id`,`sitic`.`inv_item_user`.`username` AS `username`,`sitic`.`inv_item_user`.`inv_purchase_item_id` AS `inv_purchase_item_id`,`sitic`.`inv_item_user`.`date_asigned` AS `date_asigned`,`sitic`.`inv_item_user`.`date_released` AS `date_released`,`sitic`.`inv_item_user`.`description` AS `description`,`sitic`.`inv_item_user`.`status` AS `status` from (`sitic`.`inv_item_user` join `sitic`.`inv_purchase_item`) where (`sitic`.`inv_purchase_item`.`id` = `sitic`.`inv_item_user`.`inv_purchase_item_id`);

-- -----------------------------------------------------
-- View `sitic`.`inv_items_unassigned`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `sitic`.`inv_items_unassigned` ;
DROP TABLE IF EXISTS `sitic`.`inv_items_unassigned`;
USE `sitic`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`sitic`@`localhost` SQL SECURITY DEFINER VIEW `sitic`.`inv_items_unassigned` AS select distinct `sitic`.`inv_purchase_item`.`id` AS `id`,`sitic`.`inv_purchase_item`.`description` AS `description`,`sitic`.`inv_purchase_item`.`amount` AS `amount`,`sitic`.`inv_purchase_item`.`control_code` AS `control_code`,`sitic`.`inv_purchase_item`.`inv_models_id` AS `inv_models_id`,`sitic`.`inv_purchase_item`.`serial_number` AS `serial_number`,`sitic`.`inv_purchase_item`.`inv_purchase_id` AS `inv_purchase_id` from (`sitic`.`inv_purchase_item` left join `sitic`.`inv_item_user` on((`sitic`.`inv_item_user`.`inv_purchase_item_id` = `sitic`.`inv_purchase_item`.`id`))) where isnull(`sitic`.`inv_item_user`.`id`) order by `sitic`.`inv_purchase_item`.`description`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sitic`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`user` (`id`, `username`, `auth_key`, `status`, `created_at`, `updated_at`) VALUES (1, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 1, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`migration`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m000000_000000_base', 1535389427);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m140506_102106_rbac_init', 1535389435);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m161220_101944_create_user_table', 1535389442);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m170907_052038_rbac_add_index_on_auth_assignment_user_id', 1535389435);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`auth_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolAdministrador', 2, 'Permiso Rol Administrador', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolUsuario', 2, 'Permiso Rol Usuario', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_administradores', 1, NULL, NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_usuarios', 1, NULL, NULL, NULL, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`auth_item_child`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_administradores', 'rolAdministrador');
INSERT INTO `sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_usuarios', 'rolUsuario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`auth_assignment`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`auth_assignment` (`item_name`, `user_id`, `created_at`) VALUES ('yii2_administradores', '1', 1535389590);

COMMIT;

