-- MySQL Script generated by MySQL Workbench
-- Sat May 23 00:57:11 2020
-- Model: SITIC    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wa_sitic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wa_sitic` ;

-- -----------------------------------------------------
-- Schema wa_sitic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wa_sitic` DEFAULT CHARACTER SET utf8mb4 ;
USE `wa_sitic` ;

-- -----------------------------------------------------
-- Table `wa_sitic`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`department` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DEPARTAMENTO',
  `department` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DEPARTAMENTO',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT 'DEPARTAMENTO PADRE',
  `status` INT(11) NOT NULL COMMENT 'ESTADO DEPARTAMENTO',
  PRIMARY KEY (`id`),
  INDEX `fk_department_department1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_department1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wa_sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`documents` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`documents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DOCUMENTO',
  `filename` VARCHAR(255) NOT NULL COMMENT 'NOMBRE DOCUMENTO',
  `filetype` VARCHAR(45) NOT NULL COMMENT 'TIPO DOCUMENTO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE DOCUMENTO',
  `date` DATETIME NOT NULL COMMENT 'FECHA',
  `external_id` INT(11) NOT NULL COMMENT 'ID RELACION',
  `external_type` VARCHAR(45) NOT NULL COMMENT 'TIPO RELACION',
  `username` VARCHAR(255) NOT NULL COMMENT 'NOMBRE USUARIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_apps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_apps` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_apps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `root` INT(11) NULL DEFAULT NULL,
  `lft` INT(11) NOT NULL,
  `rgt` INT(11) NOT NULL,
  `lvl` SMALLINT(5) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  `icon_type` TINYINT(1) NOT NULL DEFAULT '1',
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `selected` TINYINT(1) NOT NULL DEFAULT '0',
  `disabled` TINYINT(1) NOT NULL DEFAULT '0',
  `readonly` TINYINT(1) NOT NULL DEFAULT '0',
  `visible` TINYINT(1) NOT NULL DEFAULT '1',
  `collapsed` TINYINT(1) NOT NULL DEFAULT '0',
  `movable_u` TINYINT(1) NOT NULL DEFAULT '1',
  `movable_d` TINYINT(1) NOT NULL DEFAULT '1',
  `movable_l` TINYINT(1) NOT NULL DEFAULT '1',
  `movable_r` TINYINT(1) NOT NULL DEFAULT '1',
  `removable` TINYINT(1) NOT NULL DEFAULT '1',
  `removable_all` TINYINT(1) NOT NULL DEFAULT '0',
  `child_allowed` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `inv_apps_NK1` (`root` ASC) VISIBLE,
  INDEX `inv_apps_NK2` (`lft` ASC) VISIBLE,
  INDEX `inv_apps_NK3` (`rgt` ASC) VISIBLE,
  INDEX `inv_apps_NK4` (`lvl` ASC) VISIBLE,
  INDEX `inv_apps_NK5` (`active` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wa_sitic`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `password` VARCHAR(255) NULL,
  `auth_key` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'LLAVE',
  `status` SMALLINT(6) NOT NULL DEFAULT '1' COMMENT 'ESTADO',
  `created_at` INT NOT NULL COMMENT 'CREADO',
  `updated_at` INT(11) NOT NULL COMMENT 'ACTUALIZADO',
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `auth_key` (`auth_key` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_manufacturers` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_manufacturers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID FABRICANTE',
  `manufacturer` VARCHAR(45) NOT NULL COMMENT 'NOMBRE FABRICANTE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `manufacturer_UNIQUE` (`manufacturer` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_models` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_models` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID MODELO',
  `model` VARCHAR(45) NOT NULL COMMENT 'NOMBRE MODELO',
  `consumables` LONGTEXT NULL DEFAULT NULL COMMENT 'CONSUMIBLES',
  `inv_manufacturers_id` INT(11) NOT NULL COMMENT 'ID FABRICANTE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC) VISIBLE,
  INDEX `fk_inv_models_inv_manufacturers1_idx` (`inv_manufacturers_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_models_inv_manufacturers1`
    FOREIGN KEY (`inv_manufacturers_id`)
    REFERENCES `wa_sitic`.`inv_manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_purchase` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID COMPRA',
  `code` VARCHAR(45) NOT NULL COMMENT 'CODIGO COMPRA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE COMPRA',
  `date` DATE NOT NULL COMMENT 'FECHA RECEPCION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_purchase_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_inv_purchase_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_purchase_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_purchase_item` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_purchase_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ITEM',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE ITEM',
  `amount` FLOAT(11) NOT NULL COMMENT 'PRECIO ITEM',
  `control_code` VARCHAR(100) NULL DEFAULT NULL COMMENT 'CODIGO CONTROL',
  `inv_models_id` INT(11) NOT NULL COMMENT 'ID MODELO',
  `serial_number` VARCHAR(45) NOT NULL COMMENT 'NUMERO SERIE',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_purchase_item_inv_purchase1_idx` (`inv_purchase_id` ASC) VISIBLE,
  INDEX `fk_inv_purchase_item_inv_models1_idx` (`inv_models_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_purchase_item_inv_models1`
    FOREIGN KEY (`inv_models_id`)
    REFERENCES `wa_sitic`.`inv_models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_purchase_item_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `wa_sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_item_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_item_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_item_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `inv_purchase_item_id` INT(11) NOT NULL COMMENT 'ID ITEM',
  `date_asigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE ASIGNACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_inv_purchase_item_inv_purchase_item1_idx` (`inv_purchase_item_id` ASC) VISIBLE,
  INDEX `fk_inv_item_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_inv_item_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_inv_purchase_item_inv_purchase_item1`
    FOREIGN KEY (`inv_purchase_item_id`)
    REFERENCES `wa_sitic`.`inv_purchase_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_apps_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_apps_category` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_apps_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `category` VARCHAR(255) NOT NULL COMMENT 'CATEGORIA',
  `parent_id` INT(11) NOT NULL COMMENT 'PADRE',
  `level` INT(11) NOT NULL COMMENT 'NIVEL',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_apps_category_it_apps_category1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_apps_category_it_apps_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wa_sitic`.`it_apps_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_incidents_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_incidents_reports` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_incidents_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID INCIDENTE',
  `subject` VARCHAR(255) NOT NULL COMMENT 'ASUNTO',
  `issue` LONGTEXT NOT NULL COMMENT 'DETALLE PROBLEMA',
  `date_reported` DATETIME NOT NULL COMMENT 'FECHA REPORTE',
  `date_solved` DATETIME NULL DEFAULT NULL COMMENT 'FECHA SOLUCION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_incidents_reports_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_incidents_reports_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_incidents_reports_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `it_incidents_reports_id` INT(11) NOT NULL COMMENT 'ID REPORTE INCIDENTE',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_it_incidents_reports_it_incidents_reports1_idx` (`it_incidents_reports_id` ASC) VISIBLE,
  INDEX `fk_it_incidents_reports_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_it_incidents_reports_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_it_incidents_reports_it_incidents_reports1`
    FOREIGN KEY (`it_incidents_reports_id`)
    REFERENCES `wa_sitic`.`it_incidents_reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_processes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_processes` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_processes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID PROCESO',
  `process` VARCHAR(255) NOT NULL COMMENT 'NOMBRE PROCESO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE PROCESO',
  `metrics` LONGTEXT NOT NULL COMMENT 'METRICA EVALUACION',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CIERRE',
  `magnitude` INT(11) NOT NULL COMMENT 'IMPORTANCIA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID PROYECTO',
  `code` VARCHAR(45) NOT NULL COMMENT 'CODIGO PROYECTO',
  `project` VARCHAR(255) NOT NULL COMMENT 'NOMBRE PROYECTO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION PROYECTO',
  `amount` FLOAT(11) NOT NULL COMMENT 'MONTO COSTO',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CIERRE',
  `status` INT(11) NOT NULL COMMENT 'ESTADO PROYECTO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_processes_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_processes_projects` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_processes_projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO\\n',
  `status` INT(11) NOT NULL COMMENT 'ESTADO\\n',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_it_projects_it_projects1_idx` (`it_projects_id` ASC) VISIBLE,
  INDEX `fk_it_processes_has_it_projects_it_processes1_idx` (`it_processes_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_processes_has_it_projects_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `wa_sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_it_projects_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_processes_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_processes_purchase` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_processes_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_inv_purchase_inv_purchase1_idx` (`inv_purchase_id` ASC) VISIBLE,
  INDEX `fk_it_processes_has_inv_purchase_it_processes1_idx` (`it_processes_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_processes_has_inv_purchase_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `wa_sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_inv_purchase_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `wa_sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_services` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID SERVICIO',
  `service` VARCHAR(255) NOT NULL COMMENT 'NOMBRE SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION SERVICIO',
  `type` VARCHAR(255) NOT NULL COMMENT 'TIPO SERVICIO',
  `date_renovation` DATE NULL DEFAULT NULL COMMENT 'FECHA RENOVACION',
  `date_creation` DATE NOT NULL COMMENT 'FECHA CREACION',
  `date_closed` DATE NULL DEFAULT NULL COMMENT 'FECHA CULMINACION',
  `stakeholders` VARCHAR(255) NOT NULL COMMENT 'BENEFICIARIOS',
  `magnitude` INT(11) NOT NULL COMMENT 'IMPORTANCIA DEL SERVICIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO PROCESO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_processes_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_processes_services` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_processes_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_processes_has_it_services_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  INDEX `fk_it_processes_has_it_services_it_processes1_idx` (`it_processes_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_processes_has_it_services_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `wa_sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_processes_has_it_services_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_processes_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_processes_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_processes_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_processes_id` INT(11) NOT NULL COMMENT 'ID PROCESO',
  `description` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'DETALLE ASIGNACION',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_it_processes_it_processes1_idx` (`it_processes_id` ASC) VISIBLE,
  INDEX `fk_it_processes_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_it_processes_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_it_processes_it_processes1`
    FOREIGN KEY (`it_processes_id`)
    REFERENCES `wa_sitic`.`it_processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects_parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects_parents` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects_parents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'CODIGO PROYECTO',
  `parent_id` INT(11) NOT NULL COMMENT 'PROYECTO RELACIONADO',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO RELACION',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_has_it_projects_it_projects2_idx` (`it_projects_id` ASC) VISIBLE,
  INDEX `fk_it_projects_has_it_projects_it_projects1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_projects_has_it_projects_it_projects1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_has_it_projects_it_projects2`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects_purchase` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects_purchase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_has_inv_purchase_inv_purchase1_idx` (`inv_purchase_id` ASC) VISIBLE,
  INDEX `fk_it_projects_has_inv_purchase_it_projects1_idx` (`it_projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_projects_has_inv_purchase_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `wa_sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_has_inv_purchase_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects_services` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects_services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_it_projects_it_projects1_idx` (`it_projects_id` ASC) VISIBLE,
  INDEX `fk_it_services_has_it_projects_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_services_has_it_projects_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_has_it_projects_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects_stages` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects_stages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO ETAPA',
  `project_stage` VARCHAR(255) NOT NULL COMMENT 'ETAPA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `percent` DOUBLE NOT NULL COMMENT 'PORCENTAJE',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_projects_stages_it_projects1_idx` (`it_projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_projects_stages_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_projects_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_projects_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_projects_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_projects_id` INT(11) NOT NULL COMMENT 'ID PROYECTO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION ASIGNACION',
  `date_asigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` VARCHAR(45) NOT NULL COMMENT 'ESTADO ASIGNACION',
  INDEX `fk_it_projects_has_user_it_projects1_idx` (`it_projects_id` ASC) VISIBLE,
  INDEX `fk_it_projects_user_user1_idx` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_it_projects_has_user_it_projects1`
    FOREIGN KEY (`it_projects_id`)
    REFERENCES `wa_sitic`.`it_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_projects_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_reports_powerbi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_reports_powerbi` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_reports_powerbi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID REPORTE',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `url` LONGTEXT NOT NULL COMMENT 'URL',
  `html_iframe` LONGTEXT NOT NULL COMMENT 'HTML IFRAME',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_services_affectations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_services_affectations` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_services_affectations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID AFECTACION',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `it_incidents_reports_id` INT(11) NOT NULL COMMENT 'ID INCIDENTE',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `affected_users` INT(11) NOT NULL COMMENT 'USUARIOS AFECTADOS',
  `affected_time` INT(11) NOT NULL COMMENT 'TIEMPO MINUTOS',
  `type` INT(11) NOT NULL COMMENT 'TIPO AFECTACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_it_incidents_reports_it_incidents_report_idx` (`it_incidents_reports_id` ASC) VISIBLE,
  INDEX `fk_it_services_has_it_incidents_reports_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_services_has_it_incidents_reports_it_incidents_reports1`
    FOREIGN KEY (`it_incidents_reports_id`)
    REFERENCES `wa_sitic`.`it_incidents_reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_has_it_incidents_reports_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_services_availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_services_availability` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_services_availability` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DISPONIBILIDAD',
  `it_services_id` INT(11) NOT NULL,
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `date_start` DATE NOT NULL COMMENT 'FECHA INICIO',
  `date_end` DATE NOT NULL COMMENT 'FECHA FIN',
  `availability_time` INT(11) NOT NULL COMMENT 'TIEMPO MINUTOS',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_availability_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_services_availability_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_services_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_services_result` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_services_result` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RESULTADO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `year` INT(11) NOT NULL COMMENT 'AÑO',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `percent` DOUBLE NOT NULL COMMENT 'PORCENTAJE',
  `date` DATETIME NOT NULL COMMENT 'FECHA',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_result_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_services_result_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_services_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_services_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_services_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID ASIGNACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `it_services_id` INT(11) NOT NULL COMMENT 'ID SERVICIO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION ASIGNACION',
  `date_assigned` DATE NOT NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATE NULL DEFAULT NULL COMMENT 'FECHA LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO ASIGNACION',
  PRIMARY KEY (`id`),
  INDEX `fk_it_services_has_user_it_services1_idx` (`it_services_id` ASC) VISIBLE,
  INDEX `fk_it_services_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_it_services_has_user_it_services1`
    FOREIGN KEY (`it_services_id`)
    REFERENCES `wa_sitic`.`it_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_services_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`logs` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` VARCHAR(255) NOT NULL COMMENT 'TIPO',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  `datetime` DATETIME NOT NULL COMMENT 'FECHA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `ipaddress` VARCHAR(255) NULL COMMENT 'IP',
  `external_id` VARCHAR(255) NULL COMMENT 'ID EXTERNO',
  `external_type` VARCHAR(255) NULL COMMENT 'TIPO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`migration` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`migration` (
  `version` VARCHAR(180) NOT NULL COMMENT 'VERSION',
  `apply_time` INT(11) NULL DEFAULT NULL COMMENT 'FECHA',
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`phones_extensions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`phones_extensions` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`phones_extensions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID EXTENSION',
  `extension` VARCHAR(45) NOT NULL COMMENT 'NUMERO EXTENSION',
  `description` VARCHAR(255) NOT NULL COMMENT 'DETALLE EXTENSION',
  `ipv4_address` VARCHAR(15) NOT NULL COMMENT 'IPV4 TELEFONO',
  `username` VARCHAR(255) NOT NULL COMMENT 'NOMBRE USUARIO',
  `department_id` INT(11) NOT NULL COMMENT 'ID DEPARTAMENTO',
  `inv_purchase_item_id` INT(11) NOT NULL COMMENT 'ID ITEM',
  PRIMARY KEY (`id`),
  INDEX `fk_phones_extensions_inv_purchase_item1_idx` (`inv_purchase_item_id` ASC) VISIBLE,
  INDEX `fk_phones_extensions_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_phones_extensions_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `wa_sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_extensions_inv_purchase_item1`
    FOREIGN KEY (`inv_purchase_item_id`)
    REFERENCES `wa_sitic`.`inv_purchase_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`phones_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`phones_logs` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`phones_logs` (
  `id` INT(11) NOT NULL COMMENT 'ID LLAMADA',
  `date` DATETIME NULL DEFAULT NULL COMMENT 'FECHA LLAMADA',
  `source` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ORIGEN LLAMADA',
  `destination` VARCHAR(45) NULL DEFAULT NULL COMMENT 'DESTINO LLAMADA',
  `src_channel` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CANAL ORIGEN',
  `dst_channel` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CANAL DESTINO',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ESTADO LLAMADA',
  `time` INT(11) NULL DEFAULT NULL COMMENT 'TIEMPO DURACION LLAMADA',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`printers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`printers` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`printers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID IMPRESORA',
  `printer` VARCHAR(255) NOT NULL COMMENT 'NOMBRE IMPRESORA',
  `ipv4_address` VARCHAR(15) NOT NULL COMMENT 'IP IMPRESORA',
  `serial_number` VARCHAR(45) NOT NULL COMMENT 'NUMERO SERIE',
  `department_id` INT(11) NOT NULL COMMENT 'ID DEPARTAMENTO',
  `inv_models_id` INT(11) NOT NULL COMMENT 'ID MODELO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO IMPRESORA',
  PRIMARY KEY (`id`),
  INDEX `fk_printers_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_printers_inv_models1_idx` (`inv_models_id` ASC) VISIBLE,
  CONSTRAINT `fk_printers_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `wa_sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_printers_inv_models1`
    FOREIGN KEY (`inv_models_id`)
    REFERENCES `wa_sitic`.`inv_models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`printers_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`printers_logs` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`printers_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID LOGS IMPRESION',
  `date` DATETIME NULL DEFAULT NULL COMMENT 'FECHA Y HORA IMPRESION',
  `username` VARCHAR(255) NULL DEFAULT NULL COMMENT 'NOMBRE DE USUARIO',
  `pages` INT(11) NULL DEFAULT NULL COMMENT 'NUMERO DE PAGINAS',
  `copies` INT(11) NULL DEFAULT NULL COMMENT 'NUMERO DE COPIAS',
  `printer` VARCHAR(255) NULL DEFAULT NULL COMMENT 'NOMBRE IMPRESORA',
  `document` LONGTEXT NULL DEFAULT NULL COMMENT 'NOMBRE DOCUMENTO',
  `client` VARCHAR(45) NULL DEFAULT NULL COMMENT 'NOMBRE DISPOSITIVO',
  `paper` VARCHAR(45) NULL DEFAULT NULL COMMENT 'FORMATO PAPEL',
  `protocol` VARCHAR(45) NULL DEFAULT NULL COMMENT 'PROTOCOLO IMPRESION',
  `high` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ALTO HOJA',
  `width` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ANCHO HOJA',
  `duplex` VARCHAR(45) NULL DEFAULT NULL COMMENT 'OPCION DUPLEX',
  `grayscale` VARCHAR(45) NULL DEFAULT NULL COMMENT 'IMPRESION CON ESCALA DE GRISES',
  `size` VARCHAR(45) NULL DEFAULT NULL COMMENT 'TAMANO DEL ARCHIVO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 195302
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`tab_int_encuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`tab_int_encuestas` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`tab_int_encuestas` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ObjectID` INT(11) NULL DEFAULT NULL,
  `GlobalID` VARCHAR(255) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  `Creator` VARCHAR(255) NULL DEFAULT NULL,
  `EditDate` DATETIME NULL DEFAULT NULL,
  `Editor` VARCHAR(255) NULL DEFAULT NULL,
  `CedulaPasaporte` VARCHAR(50) NULL DEFAULT NULL,
  `Nombres` VARCHAR(255) NULL DEFAULT NULL,
  `Apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Campus` VARCHAR(255) NULL DEFAULT NULL,
  `Carrera` VARCHAR(255) NULL DEFAULT NULL,
  `Telefono` VARCHAR(255) NULL DEFAULT NULL,
  `Operadora` VARCHAR(255) NULL DEFAULT NULL,
  `Internet` VARCHAR(255) NULL DEFAULT NULL,
  `TipoInternet` VARCHAR(255) NULL DEFAULT NULL,
  `Computador` VARCHAR(255) NULL DEFAULT NULL,
  `TipoComputador` VARCHAR(255) NULL DEFAULT NULL,
  `PropiedadComputador` VARCHAR(255) NULL DEFAULT NULL,
  `x` VARCHAR(255) NULL DEFAULT NULL,
  `y` VARCHAR(255) NULL DEFAULT NULL,
  `Beneficio` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3149
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wa_sitic`.`auth_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`auth_rule` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`auth_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`auth_item` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `type` SMALLINT(6) NOT NULL COMMENT 'TIPO',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'DETALLE',
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL DEFAULT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC) VISIBLE,
  INDEX `idx-auth_item-type` (`type` ASC) VISIBLE,
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `wa_sitic`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`auth_item_child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`auth_item_child` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL PADRE',
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL HIJO',
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC) VISIBLE,
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `wa_sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `wa_sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`auth_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`auth_assignment` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `auth_assignment_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `wa_sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`registration` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `company` VARCHAR(255) NOT NULL COMMENT 'EMPRESA',
  `mail` VARCHAR(255) NOT NULL COMMENT 'EMAIL CONTACTO',
  `address` VARCHAR(255) NOT NULL COMMENT 'DIRECCION',
  `phone` VARCHAR(45) NOT NULL COMMENT 'TELEFONO',
  `status` SMALLINT(6) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'CREADO\\n',
  `updated_at` DATETIME NOT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`user_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`user_department` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`user_department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID RELACION',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'NOMBRE USUARIO',
  `department_id` INT(11) NOT NULL COMMENT 'ID DEPARTAMENTO',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_department_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_user_department_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_department_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_department_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `wa_sitic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_apps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_apps` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_apps` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` VARCHAR(255) NOT NULL COMMENT 'ETIQUETA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `username` VARCHAR(255) NULL COMMENT 'USUARIO',
  `password` LONGTEXT NULL COMMENT 'CONTRASEÑA',
  `email` VARCHAR(255) NULL COMMENT 'EMAIL',
  `url` VARCHAR(255) NULL COMMENT 'URL',
  `status` INT NOT NULL COMMENT 'ESTADO',
  `it_apps_category_id` INT(11) NOT NULL COMMENT 'CATEGORIA',
  PRIMARY KEY (`id`),
  INDEX `fk_it_apps_it_apps_category1_idx` (`it_apps_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_apps_it_apps_category1`
    FOREIGN KEY (`it_apps_category_id`)
    REFERENCES `wa_sitic`.`it_apps_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`user_profile` (
  `dni` VARCHAR(50) NULL COMMENT 'DNI/CEDULA/PASAPORTE',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `firstname` VARCHAR(255) NULL COMMENT 'NOMBRES',
  `lastname` VARCHAR(255) NULL COMMENT 'APELLIDOS',
  `commonname` VARCHAR(255) NULL COMMENT 'NOM. COMPLETO',
  `displayname` VARCHAR(255) NULL COMMENT 'NOM. MOSTRAR',
  `mail` VARCHAR(255) NOT NULL COMMENT 'EMAIL',
  `personalmail` VARCHAR(255) NULL COMMENT 'EMAIL PERSONAL',
  `mobile` VARCHAR(50) NULL COMMENT 'CELULAR',
  INDEX `fk_user_data_user1_idx` (`username` ASC) VISIBLE,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_user_data_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_licenses` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `license` VARCHAR(255) NOT NULL COMMENT 'LICENCIA',
  `quantity` VARCHAR(45) NOT NULL COMMENT 'CANTIDAD',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `serial_number` VARCHAR(255) NULL COMMENT 'NUMERO DE SERIE',
  `valid_since` DATE NULL COMMENT 'VALIDO DESDE',
  `valid_until` DATE NULL COMMENT 'VALIDO HASTA',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  `inv_manufacturers_id` INT(11) NOT NULL COMMENT 'FABRICANTE',
  PRIMARY KEY (`id`),
  INDEX `fk_it_licenses_inv_manufacturers1_idx` (`inv_manufacturers_id` ASC) VISIBLE,
  CONSTRAINT `fk_it_licenses_inv_manufacturers1`
    FOREIGN KEY (`inv_manufacturers_id`)
    REFERENCES `wa_sitic`.`inv_manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`it_licenses_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`it_licenses_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`it_licenses_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `it_licenses_id` INT NOT NULL COMMENT 'LICENCIA',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `description` LONGTEXT NOT NULL COMMENT 'DESCRIPCION',
  `date_assigned` DATE NOT NULL COMMENT 'FEC. ASIGNACION',
  `date_released` DATE NOT NULL COMMENT 'FEC. LIBERACION',
  `status` INT(11) NOT NULL COMMENT 'ESTADO',
  INDEX `fk_user_has_it_licenses_it_licenses1_idx` (`it_licenses_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_it_licenses_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_it_licenses_it_licenses1`
    FOREIGN KEY (`it_licenses_id`)
    REFERENCES `wa_sitic`.`it_licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_it_licenses_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wa_sitic`.`tab_int_senescyt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`tab_int_senescyt` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`tab_int_senescyt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fec_inicio` DATETIME NULL,
  `fec_fin` DATETIME NULL,
  `email` VARCHAR(255) NULL,
  `nombres` VARCHAR(255) NULL,
  `cedula_pasaporte` VARCHAR(255) NULL,
  `provincia` VARCHAR(255) NULL,
  `canton` VARCHAR(255) NULL,
  `parroquia` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `nivel` VARCHAR(255) NULL,
  `carrera` VARCHAR(255) NULL,
  `semestre` VARCHAR(255) NULL,
  `equipos` VARCHAR(255) NULL,
  `computador` VARCHAR(255) NULL,
  `portatil` VARCHAR(255) NULL,
  `tablet` VARCHAR(255) NULL,
  `radio` VARCHAR(255) NULL,
  `television` VARCHAR(255) NULL,
  `smartphone` VARCHAR(255) NULL,
  `mic_computador` VARCHAR(255) NULL,
  `cam_computador` VARCHAR(255) NULL,
  `par_computador` VARCHAR(255) NULL,
  `mic_portatil` VARCHAR(255) NULL,
  `cam_portatil` VARCHAR(255) NULL,
  `par_portatil` VARCHAR(255) NULL,
  `internet` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  `proveedor` VARCHAR(255) NULL,
  `velocidad` VARCHAR(255) NULL,
  `teletrabajo` VARCHAR(255) NULL,
  `estudios` VARCHAR(255) NULL,
  `cant_usuarios` VARCHAR(255) NULL,
  `horas` VARCHAR(255) NULL,
  `accion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`tab_int_formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`tab_int_formulario` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`tab_int_formulario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cedula` VARCHAR(255) NULL COMMENT 'CEDULA',
  `username` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `nombres` VARCHAR(255) NULL COMMENT 'NOMBRES',
  `apellidos` VARCHAR(255) NULL COMMENT 'APELLIDOS',
  `codigo_postal` VARCHAR(255) NULL COMMENT 'CODIGO POSTAL',
  `provincia` VARCHAR(255) NULL COMMENT 'PROVINCIA',
  `canton` VARCHAR(255) NULL COMMENT 'CANTON',
  `parroquia` VARCHAR(255) NULL COMMENT 'PARROQUIA',
  `calle_principal` VARCHAR(255) NULL COMMENT 'CALLE PRINCIPAL',
  `calle_secundaria` VARCHAR(255) NULL COMMENT 'CALLE SECUNDARIA',
  `referencia_texto` VARCHAR(255) NULL COMMENT 'REFERENCIA TEXTO',
  `referencia_foto` VARCHAR(255) NULL COMMENT 'REFERENCIA FOTO',
  `cel_contacto` VARCHAR(255) NULL COMMENT 'CELULAR CONTACTO',
  `tel_contacto` VARCHAR(255) NULL COMMENT 'TELEFONO CONTACTO',
  `siad_matriculado` VARCHAR(255) NULL COMMENT 'SIAD MATRICULADO',
  `siad_semestre` VARCHAR(255) NULL COMMENT 'SIAD SEMESTRE',
  `siad_carrera` VARCHAR(255) NULL COMMENT 'SIAD CARRERA',
  `ficha_escasos_recursos` VARCHAR(255) NULL COMMENT 'FICHA ESCASOS RECURSOS',
  `encuesta_beneficiario` VARCHAR(255) NULL COMMENT 'ENCUESTA BENEFICIARIO',
  `condiciones` VARCHAR(255) NULL COMMENT 'CONDICIONES',
  `contrato` VARCHAR(255) NULL COMMENT 'CONTRATO',
  `qrcode` VARCHAR(255) NULL COMMENT 'CODIGO QR',
  `status` INT(11) NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_purchase_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_purchase_service` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_purchase_service` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `inv_purchase_id` INT(11) NOT NULL COMMENT 'ID COMPRA',
  `description` LONGTEXT NULL COMMENT 'DESCRIPCION',
  `amount` FLOAT(11) NULL COMMENT 'COSTO',
  `control_code` VARCHAR(255) NULL COMMENT 'CODIGO',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_purchase_service_inv_purchase1_idx` (`inv_purchase_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_purchase_service_inv_purchase1`
    FOREIGN KEY (`inv_purchase_id`)
    REFERENCES `wa_sitic`.`inv_purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`inv_service_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_service_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_service_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `inv_purchase_service_id` INT NOT NULL COMMENT 'ID SERVICIO',
  `date_assigned` DATETIME NULL COMMENT 'FECHA ASIGNACION',
  `date_released` DATETIME NULL COMMENT 'FECHA LIBERACION',
  `description` LONGTEXT NULL COMMENT 'DESCRIPCION',
  `status` INT(11) NULL COMMENT 'ESTADO',
  PRIMARY KEY (`id`),
  INDEX `fk_inv_service_user_inv_purchase_service1_idx` (`inv_purchase_service_id` ASC) VISIBLE,
  INDEX `fk_inv_service_user_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_inv_service_user_inv_purchase_service1`
    FOREIGN KEY (`inv_purchase_service_id`)
    REFERENCES `wa_sitic`.`inv_purchase_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_service_user_user1`
    FOREIGN KEY (`username`)
    REFERENCES `wa_sitic`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`tab_int_formulario_inv_service_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`tab_int_formulario_inv_service_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`tab_int_formulario_inv_service_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tab_int_formulario_id` INT NOT NULL,
  `inv_service_user_id` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tab_int_formulario_inv_service_user_tab_int_formulario1_idx` (`tab_int_formulario_id` ASC) VISIBLE,
  INDEX `fk_tab_int_formulario_inv_service_user_inv_service_user1_idx` (`inv_service_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_int_formulario_inv_service_user_tab_int_formulario1`
    FOREIGN KEY (`tab_int_formulario_id`)
    REFERENCES `wa_sitic`.`tab_int_formulario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_int_formulario_inv_service_user_inv_service_user1`
    FOREIGN KEY (`inv_service_user_id`)
    REFERENCES `wa_sitic`.`inv_service_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wa_sitic`.`tab_int_formulario_inv_item_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`tab_int_formulario_inv_item_user` ;

CREATE TABLE IF NOT EXISTS `wa_sitic`.`tab_int_formulario_inv_item_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tab_int_formulario_id` INT NOT NULL,
  `inv_item_user_id` INT(11) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tab_int_formulario_inv_item_user_tab_int_formulario1_idx` (`tab_int_formulario_id` ASC) VISIBLE,
  INDEX `fk_tab_int_formulario_inv_item_user_inv_item_user1_idx` (`inv_item_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_int_formulario_inv_item_user_tab_int_formulario1`
    FOREIGN KEY (`tab_int_formulario_id`)
    REFERENCES `wa_sitic`.`tab_int_formulario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_int_formulario_inv_item_user_inv_item_user1`
    FOREIGN KEY (`inv_item_user_id`)
    REFERENCES `wa_sitic`.`inv_item_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `wa_sitic` ;

-- -----------------------------------------------------
-- Placeholder table for view `wa_sitic`.`inv_items_assigned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_items_assigned` (`inv_purchase_id` INT, `id` INT, `username` INT, `inv_purchase_item_id` INT, `date_asigned` INT, `date_released` INT, `description` INT, `status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `wa_sitic`.`inv_items_unassigned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wa_sitic`.`inv_items_unassigned` (`id` INT, `description` INT, `amount` INT, `control_code` INT, `inv_models_id` INT, `serial_number` INT, `inv_purchase_id` INT);

-- -----------------------------------------------------
-- View `wa_sitic`.`inv_items_assigned`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_items_assigned`;
DROP VIEW IF EXISTS `wa_sitic`.`inv_items_assigned` ;
USE `wa_sitic`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`wa_sitic`@`localhost` SQL SECURITY DEFINER VIEW `wa_sitic`.`inv_items_assigned` AS select distinct `wa_sitic`.`inv_purchase_item`.`inv_purchase_id` AS `inv_purchase_id`,`wa_sitic`.`inv_item_user`.`id` AS `id`,`wa_sitic`.`inv_item_user`.`username` AS `username`,`wa_sitic`.`inv_item_user`.`inv_purchase_item_id` AS `inv_purchase_item_id`,`wa_sitic`.`inv_item_user`.`date_asigned` AS `date_asigned`,`wa_sitic`.`inv_item_user`.`date_released` AS `date_released`,`wa_sitic`.`inv_item_user`.`description` AS `description`,`wa_sitic`.`inv_item_user`.`status` AS `status` from (`wa_sitic`.`inv_item_user` join `wa_sitic`.`inv_purchase_item`) where (`wa_sitic`.`inv_purchase_item`.`id` = `wa_sitic`.`inv_item_user`.`inv_purchase_item_id`);

-- -----------------------------------------------------
-- View `wa_sitic`.`inv_items_unassigned`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wa_sitic`.`inv_items_unassigned`;
DROP VIEW IF EXISTS `wa_sitic`.`inv_items_unassigned` ;
USE `wa_sitic`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`wa_sitic`@`localhost` SQL SECURITY DEFINER VIEW `wa_sitic`.`inv_items_unassigned` AS select distinct `wa_sitic`.`inv_purchase_item`.`id` AS `id`,`wa_sitic`.`inv_purchase_item`.`description` AS `description`,`wa_sitic`.`inv_purchase_item`.`amount` AS `amount`,`wa_sitic`.`inv_purchase_item`.`control_code` AS `control_code`,`wa_sitic`.`inv_purchase_item`.`inv_models_id` AS `inv_models_id`,`wa_sitic`.`inv_purchase_item`.`serial_number` AS `serial_number`,`wa_sitic`.`inv_purchase_item`.`inv_purchase_id` AS `inv_purchase_id` from (`wa_sitic`.`inv_purchase_item` left join `wa_sitic`.`inv_item_user` on((`wa_sitic`.`inv_item_user`.`inv_purchase_item_id` = `wa_sitic`.`inv_purchase_item`.`id`))) where isnull(`wa_sitic`.`inv_item_user`.`id`) order by `wa_sitic`.`inv_purchase_item`.`description`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wa_sitic`.`inv_apps`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`inv_apps` (`id`, `root`, `lft`, `rgt`, `lvl`, `name`, `icon`, `icon_type`, `active`, `selected`, `disabled`, `readonly`, `visible`, `collapsed`, `movable_u`, `movable_d`, `movable_l`, `movable_r`, `removable`, `removable_all`, `child_allowed`) VALUES (1, 1, 1, 1, 0, 'SITIC', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`user` (`id`, `username`, `password`, `auth_key`, `status`, `created_at`, `updated_at`) VALUES (1, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'F2u5myhYPc97LWK8R4jPqQL98rvVFE04', 1, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`it_apps_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`it_apps_category` (`id`, `category`, `parent_id`, `level`, `status`) VALUES (1, 'SITIC', 1, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`migration`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`migration` (`version`, `apply_time`) VALUES ('m000000_000000_base', 1535389427);
INSERT INTO `wa_sitic`.`migration` (`version`, `apply_time`) VALUES ('m140506_102106_rbac_init', 1535389435);
INSERT INTO `wa_sitic`.`migration` (`version`, `apply_time`) VALUES ('m161220_101944_create_user_table', 1535389442);
INSERT INTO `wa_sitic`.`migration` (`version`, `apply_time`) VALUES ('m170907_052038_rbac_add_index_on_auth_assignment_user_id', 1535389435);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`auth_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolAdministrador', 2, 'Permiso Rol Administrador', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `wa_sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolUsuario', 2, 'Permiso Rol Usuario', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `wa_sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_administradores', 1, NULL, NULL, NULL, 1535389590, 1535389590);
INSERT INTO `wa_sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_usuarios', 1, NULL, NULL, NULL, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`auth_item_child`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_administradores', 'rolAdministrador');
INSERT INTO `wa_sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_usuarios', 'rolUsuario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `wa_sitic`.`auth_assignment`
-- -----------------------------------------------------
START TRANSACTION;
USE `wa_sitic`;
INSERT INTO `wa_sitic`.`auth_assignment` (`item_name`, `user_id`, `created_at`) VALUES ('yii2_administradores', '1', 1535389590);

COMMIT;

