-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 03:09:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sitic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sitic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sitic` DEFAULT CHARACTER SET utf8mb4 ;
USE `sitic` ;

-- -----------------------------------------------------
-- Table `sitic`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` VARCHAR(255) NOT NULL COMMENT 'TIPO',
  `username` VARCHAR(255) NOT NULL COMMENT 'USUARIO',
  `datetime` DATETIME NOT NULL COMMENT 'FECHA',
  `description` LONGTEXT NOT NULL COMMENT 'DETALLE',
  `ipaddress` VARCHAR(255) NULL COMMENT 'IP',
  `external_id` VARCHAR(255) NULL COMMENT 'ID EXTERNO',
  `external_type` VARCHAR(255) NULL COMMENT 'TIPO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitic`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`migration` (
  `version` VARCHAR(180) NOT NULL COMMENT 'VERSION',
  `apply_time` INT(11) NULL DEFAULT NULL COMMENT 'FECHA',
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sitic`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `auth_key` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'CLAVE',
  `status` SMALLINT(6) NOT NULL DEFAULT '1' COMMENT 'ESTADO',
  `created_at` INT NOT NULL COMMENT 'CREADO',
  `updated_at` INT(11) NOT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `auth_key` (`auth_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `type` SMALLINT(6) NOT NULL COMMENT 'TIPO',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'DETALLE',
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'REGLE',
  `data` BLOB NULL COMMENT 'DATOS',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  `updated_at` INT(11) NULL DEFAULT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `idx-auth_item-type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `sitic`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL PADRE',
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL HIJO',
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ROL',
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'USUARIO',
  `created_at` INT(11) NULL COMMENT 'CREADO',
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `auth_assignment_user_id_idx` (`user_id` ASC),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `sitic`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sitic`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitic`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `company` VARCHAR(255) NOT NULL COMMENT 'EMPRESA',
  `mail` VARCHAR(255) NOT NULL COMMENT 'EMAIL CONTACTO',
  `address` VARCHAR(255) NOT NULL COMMENT 'DIRECCION',
  `phone` VARCHAR(45) NOT NULL COMMENT 'TELEFONO',
  `status` SMALLINT(6) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'CREADO\n',
  `updated_at` DATETIME NOT NULL COMMENT 'ACTUALIZADO',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sitic`.`migration`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m000000_000000_base', 1535389427);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m140506_102106_rbac_init', 1535389435);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m161220_101944_create_user_table', 1535389442);
INSERT INTO `sitic`.`migration` (`version`, `apply_time`) VALUES ('m170907_052038_rbac_add_index_on_auth_assignment_user_id', 1535389435);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`user` (`id`, `username`, `auth_key`, `status`, `created_at`, `updated_at`) VALUES (1, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 1, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`auth_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolAdministrador', 2, 'Permiso Rol Administrador', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('rolUsuario', 2, 'Permiso Rol Usuario', NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_administradores', 1, NULL, NULL, NULL, 1535389590, 1535389590);
INSERT INTO `sitic`.`auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES ('yii2_usuarios', 1, NULL, NULL, NULL, 1535389590, 1535389590);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sitic`.`auth_item_child`
-- -----------------------------------------------------
START TRANSACTION;
USE `sitic`;
INSERT INTO `sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_administradores', 'rolAdministrador');
INSERT INTO `sitic`.`auth_item_child` (`parent`, `child`) VALUES ('yii2_usuarios', 'rolUsuario');

COMMIT;

